version: '3.8'

services:
  node-app:
    image: hub.jacobstec.dev/basic-node-api:latest  # Replace with your actual Docker Hub repo
    container_name: basic-node-api
    restart: unless-stopped
    ports:
      - "3000:3000"  # Expose port 3000 on host and forward to container
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
